version: "3"
services:
  ui:
    build:
      context: ./ui
      target: builder
    volumes:
      - node-cache:/src/app/node_modules
      - ./ui:/src/app
    command: npm start

  api:
    build:
      context: ./api
    volumes:
      - ./api:/src/app
    command: flask run --host 0.0.0.0
    environment:
      - FLASK_APP=app
      - FLASK_ENV=development
      - FLASK_DEBUG=1

  proxy:
    image: nginx:alpine
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:8080

volumes:
  node-cache:
