name: CI
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  api-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install ruff without running check or format
        uses: astral-sh/ruff-action@v3
        with:
          args: "--version"
      - name: Run ruff check
        run: cd api && ruff check
      - name: Run ruff format
        run: cd api && ruff format --check

  api-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v5
      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: "api/pyproject.toml"
      - name: Install dependencies
        run: cd api && uv sync --frozen
      - name: Build the app
        run: cd api && uv build

  ui-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: cd ui && npm ci
      - name: Run lint
        run: cd ui && npm run lint

  ui-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: cd ui && npm ci
      - name: Build the app
        run: cd ui && npm run build
